name: pull docker image
description: Pull Hugging face ML Model docker image from docker hub
inputs:
    modelname:
        description: 'Model name'
        required: true
        default: 'transformers-all-latest-torch-nightly-gpu'

runs:
    using: composite
    steps:
    - name: Pull docker image
      run: |
            docker pull huggingface/${{ inputs.modelname }}
      shell: bash
