name: Pull Docker Images
description: Pulls a Hugging Face ML model or multiple Docker images from a file

inputs:
  modelname:
    description: "Single Model Name to Pull"
    required: false
    default: "transformers-all-latest-torch-nightly-gpu"
  
  filepath:
    description: "File containing list of images to pull"
    required: false

runs:
  using: composite
  steps:
    - name: Pull single Docker image
      if: inputs.filepath == ''
      run: |
        echo "Pulling single image: huggingface/${{ inputs.modelname }}"
        docker pull huggingface/${{ inputs.modelname }}
      shell: bash

    - name: Pull multiple Docker images from file
      if: inputs.filepath != ''
      run: |
        set -e  # Exit on error
        echo "Pulling multiple images from file: ${{ inputs.filepath }}"
        while IFS= read -r image; do
          echo "Pulling $image..."
          docker pull "$image"
        done < "${{ inputs.filepath }}"
      shell: bash
